# Generated by Django 3.1 on 2020-08-31 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, db_column='author', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'antares.apps.performance.models.perf_header.table_name',
                'verbose_name_plural': 'antares.apps.performance.models.perf_header.table_name_plural',
                'db_table': 'perf_header',
            },
        ),
    ]
