# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='concept_type',
            field=models.ForeignKey(
                blank=True,
                db_column='concept_type',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.ConceptType'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                db_column='currency',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.Currency'),
        ),
    ]
