# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170427_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccounttype',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
