# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_auto_20180614_2029'),
        ('client', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='document',
            field=models.ForeignKey(
                blank=True,
                db_column='document',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='document.DocumentHeader'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.ForeignKey(
                blank=True,
                db_column='transaction_type',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='accounting.TransactionType'),
        ),
        migrations.AddField(
            model_name='accountrule',
            name='account_type',
            field=models.ForeignKey(
                blank=True,
                db_column='account_type',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='accounting.AccountType'),
        ),
        migrations.AddField(
            model_name='accountrule',
            name='author',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountrule',
            name='concept_type',
            field=models.ForeignKey(
                blank=True,
                db_column='concept_type',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.ConceptType'),
        ),
        migrations.AddField(
            model_name='accountrule',
            name='fixed_client',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='client.Client'),
        ),
        migrations.AddField(
            model_name='accountrule',
            name='form_definition',
            field=models.ForeignKey(
                db_column='form_definition',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='account_rule_set',
                to='document.FormDefinition'),
        ),
        migrations.AddField(
            model_name='accountrule',
            name='transaction_type',
            field=models.ForeignKey(
                db_column='transaction_type',
                on_delete=django.db.models.deletion.PROTECT,
                to='accounting.TransactionType'),
        ),
        migrations.AddField(
            model_name='accountdocument',
            name='document',
            field=models.OneToOneField(
                db_column='document_header',
                on_delete=django.db.models.deletion.PROTECT,
                to='document.DocumentHeader'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='account_type',
            field=models.ForeignKey(
                db_column='account_type',
                on_delete=django.db.models.deletion.PROTECT,
                to='accounting.AccountType'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='base_document',
            field=models.ForeignKey(
                blank=True,
                db_column='base_document',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='account_document_base_document_set',
                to='document.DocumentHeader'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='client',
            field=models.ForeignKey(
                db_column='client',
                on_delete=django.db.models.deletion.PROTECT,
                to='client.Client'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='compliance_document',
            field=models.ForeignKey(
                blank=True,
                db_column='compliance_document',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='account_document_compliance_document_set',
                to='document.DocumentHeader'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='concept_type',
            field=models.ForeignKey(
                blank=True,
                db_column='concept_type',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.ConceptType'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='default_currency',
            field=models.ForeignKey(
                blank=True,
                db_column='default_currency',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.Currency'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together=set([('client', 'concept_type', 'period',
                                  'account_type')]),
        ),
    ]
