# Generated by Django 2.0.6 on 2018-06-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180614_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrule',
            name='fixed_client',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='client.Client'),
        ),
    ]
