# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20180202_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrule',
            options={'verbose_name': 'Regla de Cuenta Corriente', 'verbose_name_plural': 'Reglas de Cuenta Corriente'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name': 'Tipo de Cuenta Corriente', 'verbose_name_plural': 'Tipos de Cuenta Corriente'},
        ),
        migrations.AlterModelOptions(
            name='glaccounttype',
            options={'verbose_name': 'Tipo de Cuenta de Libro Mayor', 'verbose_name_plural': 'Tipos de Cuenta de Libro Mayor'},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'verbose_name': 'Tipo de Transacción', 'verbose_name_plural': 'Tipo de Transacción'},
        ),
    ]
