# Generated by Django 2.2.9 on 2020-02-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcharge',
            name='period',
            field=models.IntegerField(),
        ),
    ]
