# Generated by Django 2.2.9 on 2020-02-09 01:37

import antares.apps.accounting.constants

from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20200208_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcharge',
            name='charge_type',
            field=enumfields.fields.EnumField(enum=antares.apps.accounting.constants.TransactionAffectedValueType, max_length=10),
        ),
    ]
