# Generated by Django 2.2.9 on 2020-02-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200120_1817'),
        ('accounting', '0010_auto_20200208_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestdefinition',
            name='concept_type',
            field=models.ForeignKey(blank=True, db_column='concept_type', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ConceptType'),
        ),
        migrations.AddField(
            model_name='penaltydefinition',
            name='concept_type',
            field=models.ForeignKey(blank=True, db_column='concept_type', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ConceptType'),
        ),
    ]
