# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180218_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrule',
            options={
                'verbose_name': 'Account Rule',
                'verbose_name_plural': 'Account Rules'
            },
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types'
            },
        ),
        migrations.AlterModelOptions(
            name='glaccounttype',
            options={
                'verbose_name': 'General Ledger Account Type',
                'verbose_name_plural': 'General Ledger Account Types'
            },
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types'
            },
        ),
    ]
