# Generated by Django 2.2.9 on 2020-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20200208_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltydefinition',
            name='max_rounds',
            field=models.IntegerField(null=True),
        ),
    ]
