# Generated by Django 2.2.9 on 2020-02-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20200210_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penaltydefinition',
            old_name='fixed_rates',
            new_name='fixed_rate',
        ),
        migrations.RenameField(
            model_name='penaltydefinition',
            old_name='fixed_rates_currency',
            new_name='fixed_rate_currency',
        ),
    ]
