# Generated by Django 2.2.9 on 2020-02-10 16:45

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20200210_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltydefinition',
            name='fixed_rate',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='penaltydefinition',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
