# Generated by Django 2.2.9 on 2020-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20200210_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestdefinition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='penaltydefinition',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
