# Generated by Django 2.2.9 on 2020-02-28 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190629_1936'),
        ('core', '0004_auto_20200120_1817'),
        ('accounting', '0018_auto_20200228_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcharge',
            name='interest_definition',
            field=models.ForeignKey(blank=True, db_column='interest_definition', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_charge_interest_definition_set', to='accounting.InterestDefinition'),
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='penalty_definition',
            field=models.ForeignKey(blank=True, db_column='penalty_definition', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_charge_penalty_definition_set', to='accounting.PenaltyDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='accountcharge',
            unique_together={('client', 'concept_type', 'period', 'account_type', 'charge_period', 'interest_definition', 'penalty_definition')},
        ),
        migrations.RemoveField(
            model_name='accountcharge',
            name='charge_type',
        ),
    ]
