# Generated by Django 3.0.4 on 2020-03-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20180624_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityapplicationdefinition',
            name='scope',
            field=models.CharField(choices=[('Same', 'antares.apps.flow.constantsActivityApplicationDefinitionScopeType.SAME'), ('Blank', 'antares.apps.flow.constantsActivityApplicationDefinitionScopeType.BLANK'), ('Dialog', 'antares.apps.flow.constantsActivityApplicationDefinitionScopeType.DIALOG')], default='Same', max_length=30),
        ),
        migrations.AlterField(
            model_name='activitydefinition',
            name='activity_type',
            field=models.CharField(choices=[('Route', 'antares.apps.flow.constants.ActivityType.ROUTE'), ('Task', 'antares.apps.flow.constants.ActivityType.TASK'), ('No Implementation', 'antares.apps.flow.constants.ActivityType.NO_IMPLEMENTATION'), ('Sub Flow', 'antares.apps.flow.constants.ActivityType.SUBFLOW')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitydefinition',
            name='assignment_strategy',
            field=models.CharField(blank=True, choices=[('Dirty Random', 'antares.apps.flow.constants.AssignmentStrategyType.DIRTY_RANDOM'), ('Random', 'antares.apps.flow.constants.AssignmentStrategyType.RANDOM'), ('Property', 'antares.apps.flow.constants.AssignmentStrategyType.PROPERTY'), ('Activity', 'antares.apps.flow.constants.AssignmentStrategyType.ACTIVITY'), ('Workload', 'antares.apps.flow.constants.AssignmentStrategyType.WORKLOAD'), ('None', 'antares.apps.flow.constants.AssignmentStrategyType.NONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='activitydefinition',
            name='finish_mode',
            field=models.CharField(choices=[('Automatic', 'antares.apps.flow.constants.ExecutionModeType.AUTOMATIC'), ('Manual', 'antares.apps.flow.constants.ExecutionModeType.MANUAL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitydefinition',
            name='instantiation',
            field=models.CharField(blank=True, choices=[('Once', 'antares.apps.flow.constants.FlowActivityInstantiationType.ONCE'), ('Multiple', 'antares.apps.flow.constants.FlowActivityInstantiationType.MULTIPLE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='activitydefinition',
            name='start_mode',
            field=models.CharField(choices=[('Automatic', 'antares.apps.flow.constants.ExecutionModeType.AUTOMATIC'), ('Manual', 'antares.apps.flow.constants.ExecutionModeType.MANUAL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Active', 'Active'), ('Created', 'Created'), ('Reassigned', 'Reassigned')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationdefinition',
            name='definition_site',
            field=models.CharField(choices=[('Package', 'antares.apps.flow.constants.DefinitionSiteType.PACKAGE'), ('Flow', 'antares.apps.flow.constants.DefinitionSiteType.FLOW'), ('System', 'antares.apps.flow.constants.DefinitionSiteType.SYSTEM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationparameterdefinition',
            name='data_type',
            field=models.CharField(choices=[('Basic', 'antares.apps.flow.constants.FlowDataType.BASIC'), ('Enumeration', 'antares.apps.flow.constants.FlowDataType.ENUMERATION')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationparameterdefinition',
            name='definition_site',
            field=models.CharField(choices=[('Package', 'antares.apps.flow.constants.DefinitionSiteType.PACKAGE'), ('Flow', 'antares.apps.flow.constants.DefinitionSiteType.FLOW'), ('System', 'antares.apps.flow.constants.DefinitionSiteType.SYSTEM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationparameterdefinition',
            name='property_type',
            field=models.CharField(choices=[('Data Field', 'antares.apps.flow.constants.PropertyType.DATA_FIELD'), ('Formal Parameter', 'antares.apps.flow.constants.PropertyType.FORMAL_PARAMETER')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationparameterdefinition',
            name='sub_data_type',
            field=models.CharField(blank=True, choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentlist',
            name='assigment_strategy',
            field=models.CharField(choices=[('Dirty Random', 'antares.apps.flow.constants.AssignmentStrategyType.DIRTY_RANDOM'), ('Random', 'antares.apps.flow.constants.AssignmentStrategyType.RANDOM'), ('Property', 'antares.apps.flow.constants.AssignmentStrategyType.PROPERTY'), ('Activity', 'antares.apps.flow.constants.AssignmentStrategyType.ACTIVITY'), ('Workload', 'antares.apps.flow.constants.AssignmentStrategyType.WORKLOAD'), ('None', 'antares.apps.flow.constants.AssignmentStrategyType.NONE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowactiondefinition',
            name='action_type',
            field=models.CharField(choices=[('Preaction', 'antares.apps.core.constants.ActionType.PRE_ACTION'), ('Postaction', 'antares.apps.core.constants.ActionType.PRE_ACTION')], default='Postaction', max_length=30),
        ),
        migrations.AlterField(
            model_name='flowactiondefinition',
            name='script_engine',
            field=models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowactivity',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Active', 'Active'), ('Created', 'Created'), ('Reassigned', 'Reassigned')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowactivityvalidation',
            name='script_type',
            field=models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python')], default='Javascript', max_length=30),
        ),
        migrations.AlterField(
            model_name='flowcase',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Active', 'Active'), ('Created', 'Created')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='priority',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('High', 'High'), ('Standard', 'Standard'), ('Low', 'Low'), ('Minimal', 'Minimal')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='status',
            field=models.CharField(choices=[('CREATED', 'antares.apps.flow.constants.FlowDefinitionStatusType.CREATED'), ('UNDER_TEST', 'Under Test'), ('UNDER_REVISION', 'Under Revision'), ('RELEASED', 'Released'), ('PHASED_OUT', 'Phased out'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day'), ('Hour', 'Hour'), ('Minute', 'Minute'), ('Second', 'Second')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flowdocument',
            name='relationship',
            field=models.CharField(choices=[('Attached', 'Attached'), ('Source', 'Source')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowproperty',
            name='data_type',
            field=models.CharField(choices=[('Basic', 'antares.apps.flow.constants.FlowDataType.BASIC'), ('Enumeration', 'antares.apps.flow.constants.FlowDataType.ENUMERATION')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowproperty',
            name='sub_data_type',
            field=models.CharField(choices=[('String', 'antares.apps.flow.constants.FlowBasicDataSubtype.STRING'), ('Text', 'antares.apps.flow.constants.FlowBasicDataSubtype.TEXT'), ('Date', 'antares.apps.flow.constants.FlowBasicDataSubtype.DATE'), ('Integer', 'antares.apps.flow.constants.FlowBasicDataSubtype.INTEGER'), ('Float', 'antares.apps.flow.constants.FlowBasicDataSubtype.FLOAT'), ('Boolean', 'antares.apps.flow.constants.FlowBasicDataSubtype.BOOLEAN'), ('Reference', 'antares.apps.flow.constants.FlowBasicDataSubtype.REFERENCE'), ('Performer', 'antares.apps.flow.constants.FlowBasicDataSubtype.PERFORMER'), ('UUID', 'antares.apps.flow.constants.FlowBasicDataSubtype.UUID')], max_length=30),
        ),
        migrations.AlterField(
            model_name='participantdefinition',
            name='participant_type',
            field=models.CharField(choices=[('ROLE', 'antares.apps.flow.constants.ParticipantType.ROLE'), ('RESOURCE_SET', 'antares.apps.flow.constants.ParticipantType.RESOURCE_SET'), ('HUMAN', 'antares.apps.flow.constants.ParticipantType.HUMAN'), ('RESOURCE', 'antares.apps.flow.constants.ParticipantType.RESOURCE'), ('ORGANIZATIONAL_UNIT', 'antares.apps.flow.constants.ParticipantType.ORGANIZATIONAL_UNIT'), ('SYSTEM', 'antares.apps.flow.constants.ParticipantType.SYSTEM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='data_type',
            field=models.CharField(choices=[('Basic', 'antares.apps.flow.constants.FlowDataType.BASIC'), ('Enumeration', 'antares.apps.flow.constants.FlowDataType.ENUMERATION')], max_length=30),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='mode',
            field=models.CharField(blank=True, choices=[('IN', 'antares.apps.flow.constants.FormalParameterModeType.IN'), ('OUT', 'antares.apps.flow.constants.FormalParameterModeType.OUT'), ('IN_OUT', 'antares.apps.flow.constants.FormalParameterModeType.IN_OUT')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='property_type',
            field=models.CharField(choices=[('Data Field', 'antares.apps.flow.constants.PropertyType.DATA_FIELD'), ('Formal Parameter', 'antares.apps.flow.constants.PropertyType.FORMAL_PARAMETER')], max_length=30),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='script_engine',
            field=models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python')], max_length=30),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='sub_data_type',
            field=models.CharField(blank=True, choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transitiondefinition',
            name='transition_type',
            field=models.CharField(choices=[('CONDITION', 'antares.apps.flow.constants.TransitionType.CONDITION'), ('DEFAULT_EXCEPTION', 'antares.apps.flow.constants.TransitionType.DEFAULT_EXCEPTION'), ('EXCEPTION', 'antares.apps.flow.constants.TransitionType.EXCEPTION'), ('OTHERWISE', 'antares.apps.flow.constants.TransitionType.OTHERWISE'), ('NONE', 'antares.apps.flow.constants.TransitionType.NONE')], max_length=30),
        ),
    ]
