# Generated by Django 3.0.4 on 2020-03-25 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0003_auto_20200307_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowdefinition',
            options={'verbose_name': 'Flow Definition', 'verbose_name_plural': 'Flow Definitions'},
        ),
        migrations.AlterModelOptions(
            name='flowpackage',
            options={'verbose_name': 'Flow Package', 'verbose_name_plural': 'Flow Packages'},
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='access_level',
            field=models.CharField(editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='creation_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='description',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='display_name',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='duration',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='flow_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='flow_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='flow_package',
            field=models.ForeignKey(blank=True, db_column='flow_package', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flow_definition_set', to='flow.FlowPackage'),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='flow_version',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='hrn_script',
            field=models.CharField(blank=True, editable=False, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day'), ('Hour', 'Hour'), ('Minute', 'Minute'), ('Second', 'Second')], editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='update_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='waiting_time',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flowdefinition',
            name='working_time',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flowpackage',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowpackage',
            name='creation_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='flowpackage',
            name='package_id',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='flowpackage',
            name='package_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='flowpackage',
            name='package_version',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='flowpackage',
            name='update_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
