# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 18:19
from __future__ import unicode_literals

from antares.apps.core.constants import *
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20170608_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdefinition',
            name='time_unit',
            field=enumfields.fields.EnumField(
                blank=True, enum=TimeUnitType, max_length=10, null=True), ),
    ]
