# Generated by Django 3.1 on 2020-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20200324_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowproperty',
            name='boolean_value',
            field=models.BooleanField(null=True),
        ),
    ]
