# Generated by Django 3.1.2 on 2020-10-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20200830_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationparameterdefinition',
            name='sub_data_type',
            field=models.CharField(blank=True, choices=[('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('Datetime', 'Date time'), ('Integer', 'Integer'), ('Float', 'Float'), ('UUID', 'UUID'), ('Boolean', 'Boolean'), ('User', 'User'), ('client', 'Client'), ('document', 'Document'), ('Money', 'Money')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='sub_data_type',
            field=models.CharField(blank=True, choices=[('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('Datetime', 'Date time'), ('Integer', 'Integer'), ('Float', 'Float'), ('UUID', 'UUID'), ('Boolean', 'Boolean'), ('User', 'User'), ('client', 'Client'), ('document', 'Document'), ('Money', 'Money')], max_length=30, null=True),
        ),
    ]
