# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0001_initial'),
        ('user', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparameter',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='antares.apps.core.models.user_parameter.user_help',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.user_parameter.user'),
        ),
        migrations.AddField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.tag.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.tag.author'), ),
        migrations.AddField(
            model_name='systemparameter',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text=
                'antares.apps.core.models.system_parameter.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.system_parameter.author'
            ), ),
        migrations.AddField(
            model_name='storedfile',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.stored_file.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.stored_file.author'), ),
        migrations.AddField(
            model_name='i18nstring',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.i18n_string.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.i18n_string.author'), ),
        migrations.AddField(
            model_name='hrncode',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.hrn_code.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.hrn_code.author'), ),
        migrations.AddField(
            model_name='hrncode',
            name='flow_definition',
            field=models.ForeignKey(
                blank=True,
                db_column='flow_definition',
                help_text=
                'antares.apps.core.models.hrn_code.flow_definition_help',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='flow.FlowDefinition',
                verbose_name='antares.apps.core.models.hrn_code.flow_definition'
            ), ),
        migrations.AddField(
            model_name='hrncode',
            name='form_definition',
            field=models.ForeignKey(
                blank=True,
                db_column='form_definition',
                help_text=
                'antares.apps.core.models.hrn_code.form_definition_help',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='document.FormDefinition',
                verbose_name='antares.apps.core.models.hrn_code.form_definition'
            ), ),
        migrations.AddField(
            model_name='hrncode',
            name='organizational_unit',
            field=models.ForeignKey(
                blank=True,
                db_column='organizational_unit',
                help_text=
                'antares.apps.core.models.hrn_code.organizational_unit_help',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='user.OrgUnit',
                verbose_name=
                'antares.apps.core.models.hrn_code.organizational_unit'), ),
        migrations.AddField(
            model_name='holiday',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.holiday.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.holiday.author'), ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text=
                'antares.apps.core.models.currency_exchange_rate.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name=
                'antares.apps.core.models.currency_exchange_rate.author'), ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.ForeignKey(
                db_column='from_currency',
                help_text=
                'antares.apps.core.models.currency_exchange_rate.from_currency_help',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='from_currency_exchange_rate_set',
                to='core.Currency',
                verbose_name=
                'antares.apps.core.models.currency_exchange_rate.from_currency'
            ), ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=models.ForeignKey(
                db_column='to_currency',
                help_text=
                'antares.apps.core.models.currency_exchange_rate.to_currency_help',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='to_currency_exchange_rate_set',
                to='core.Currency',
                verbose_name=
                'antares.apps.core.models.currency_exchange_rate.to_currency'),
        ),
        migrations.AddField(
            model_name='currency',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.currency.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.currency.author'), ),
        migrations.AddField(
            model_name='concepttype',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.concept_type.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.concept_type.author'),
        ),
        migrations.AddField(
            model_name='concepttype',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text='antares.apps.core.models.concept_type.parent_help',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='core.ConceptType',
                verbose_name='antares.apps.core.models.concept_type.parent'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text='antares.apps.core.models.catalog.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.catalog.author'), ),
        migrations.AddField(
            model_name='catalog',
            name='document_header',
            field=models.ForeignKey(
                blank=True,
                db_column='document_header',
                help_text=
                'antares.apps.core.models.catalog.document_header_help',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='document.DocumentHeader',
                verbose_name='antares.apps.core.models.catalog.document_header'
            ), ),
        migrations.AddField(
            model_name='actionparameterdefinition',
            name='action_definition',
            field=models.ForeignKey(
                blank=True,
                db_column='action_definition',
                help_text=
                'antares.apps.core.models.action_parameter_definition.action_definition_help',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.ActionDefinition',
                verbose_name=
                'antares.apps.core.models.action_parameter_definition.action_definition'
            ), ),
        migrations.AddField(
            model_name='actiondefinition',
            name='author',
            field=models.ForeignKey(
                editable=False,
                help_text=
                'antares.apps.core.models.action_definition.author_help',
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.action_definition.author'
            ), ),
        migrations.AlterUniqueTogether(
            name='userparameter',
            unique_together=set([('id', 'user')]), ),
    ]
