# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 03:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170427_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemparameter',
            name='author',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text=
                'antares.apps.core.models.system_parameter.author_help',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='antares.apps.core.models.system_parameter.author'
            ),
        ),
    ]
