# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180117_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiondefinition',
            options={
                'verbose_name':
                'antares.apps.core.models.action_definition.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.action_definition.table_name_plural'
            },
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={
                'verbose_name':
                'antares.apps.core.models.catalog.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.catalog.table_name_plural'
            },
        ),
        migrations.AlterModelOptions(
            name='concepttype',
            options={
                'verbose_name':
                'antares.apps.core.models.concept_type.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.concept_type.table_name_plural'
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={
                'verbose_name':
                'antares.apps.core.models.currency.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.currency.table_name_plural'
            },
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={
                'verbose_name':
                'antares.apps.core.models.holiday.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.holiday.table_name_plural'
            },
        ),
        migrations.AlterModelOptions(
            name='hrncode',
            options={
                'verbose_name':
                'antares.apps.core.models.hrn_code.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.hrn_code.table_name_plural'
            },
        ),
        migrations.AlterModelOptions(
            name='systemparameter',
            options={
                'verbose_name':
                'antares.apps.core.models.system_parameter.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.system_parameter.table_name_plural'
            },
        ),
        migrations.AlterModelOptions(
            name='userparameter',
            options={
                'verbose_name':
                'antares.apps.core.models.user_parameter.table_name',
                'verbose_name_plural':
                'antares.apps.core.models.user_parameter.table_name_plural'
            },
        ),
    ]
