# Generated by Django 2.2.9 on 2020-01-20 21:17

import antares.apps.core.constants

from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190629_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondefinition',
            name='environment',
            field=enumfields.fields.EnumField(default='Local', enum=antares.apps.core.constants.EnvironmentType, help_text='antares.apps.core.models.action_definition.environment_help', max_length=20, verbose_name='antares.apps.core.models.action_definition.environment'),
        ),
        migrations.AlterField(
            model_name='actionparameterdefinition',
            name='data_type',
            field=enumfields.fields.EnumField(default='String', enum=antares.apps.core.constants.FieldDataType, help_text='antares.apps.core.models.action_parameter_definition.data_type_help', max_length=8, verbose_name='antares.apps.core.models.action_parameter_definition.data_type'),
        ),
    ]
