# Generated by Django 3.0.4 on 2020-03-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200120_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondefinition',
            name='environment',
            field=models.TextField(choices=[('Local', 'antares.apps.core.constants.EnvironmentType.LOCAL'), ('Web Service', 'antares.apps.core.constants.EnvironmentType.WEBSERVICE')], default='Local', help_text='antares.apps.core.models.action_definition.environment_help', max_length=20, verbose_name='antares.apps.core.models.action_definition.environment'),
        ),
        migrations.AlterField(
            model_name='actiondefinition',
            name='target_module',
            field=models.TextField(choices=[('Document', 'antares.apps.core.constants.ActionTargetModuleType.DOCUMENT'), ('Flow', 'antares.apps.core.constants.ActionTargetModuleType.FLOW')], default='Document', help_text='antares.apps.core.models.action_definition.target_module_help', max_length=30, verbose_name='antares.apps.core.models.action_definition.target_module'),
        ),
        migrations.AlterField(
            model_name='actionparameterdefinition',
            name='data_type',
            field=models.TextField(choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], default='String', help_text='antares.apps.core.models.action_parameter_definition.data_type_help', max_length=8, verbose_name='antares.apps.core.models.action_parameter_definition.data_type'),
        ),
        migrations.AlterField(
            model_name='actionparameterdefinition',
            name='direction',
            field=models.TextField(choices=[('In', 'antares.apps.core.constants.ActionParameterDirectionType.IN'), ('Out', 'antares.apps.core.constants.ActionParameterDirectionType.OUT'), ('In out', 'antares.apps.core.constants.ActionParameterDirectionType.IN_OUT')], default='In', help_text='antares.apps.core.models.action_parameter_definition.direction_help', max_length=6, verbose_name='antares.apps.core.models.action_parameter_definition.direction'),
        ),
        migrations.AlterField(
            model_name='hrncode',
            name='module_type',
            field=models.TextField(choices=[('Document', 'antares.apps.core.constants.HrnModuleType.DOCUMENT'), ('Flow Case', 'antares.apps.core.constants.HrnModuleType.FLOW_CASE'), ('Flow Activity', 'antares.apps.core.constants.HrnModuleType.FLOW_ACTIVITY'), ('Account Balance', 'antares.apps.core.constants.HrnModuleType.ACCOUNT_BALANCE'), ('Account Transaction', 'antares.apps.core.constants.HrnModuleType.ACCOUNT_TRANSACTION')], help_text='antares.apps.core.models.hrn_code.module_type_help', max_length=40, verbose_name='antares.apps.core.models.hrn_code.module_type'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='data_type',
            field=models.TextField(choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], help_text='antares.apps.core.models.system_parameter.data_type_help', max_length=20, verbose_name='antares.apps.core.models.system_parameter.data_type'),
        ),
        migrations.AlterField(
            model_name='userparameter',
            name='data_type',
            field=models.TextField(choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], help_text='antares.apps.core.models.user_parameter.data_type_help', max_length=20, verbose_name='antares.apps.core.models.user_parameter.data_type'),
        ),
    ]
