# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180214_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiondefinition',
            options={
                'verbose_name': 'Action Definition',
                'verbose_name_plural': 'Action Definition'
            },
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs'
            },
        ),
        migrations.AlterModelOptions(
            name='concepttype',
            options={
                'verbose_name': 'Concept Type',
                'verbose_name_plural': 'Concept Types'
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies'
            },
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays'
            },
        ),
        migrations.AlterModelOptions(
            name='hrncode',
            options={
                'verbose_name': 'Human Readable Code',
                'verbose_name_plural': 'Human Readable Codes'
            },
        ),
        migrations.AlterModelOptions(
            name='systemparameter',
            options={
                'verbose_name': 'System Parameter',
                'verbose_name_plural': 'System Parameters'
            },
        ),
        migrations.AlterModelOptions(
            name='userparameter',
            options={
                'verbose_name': 'User Parameter',
                'verbose_name_plural': 'User Parameters'
            },
        ),
    ]
