# Generated by Django 3.1 on 2020-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200307_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemparameter',
            name='boolean_value',
            field=models.BooleanField(blank=True, help_text='antares.apps.core.models.system_parameter.boolean_value_help', null=True, verbose_name='antares.apps.core.models.system_parameter.boolean_value'),
        ),
        migrations.AlterField(
            model_name='userparameter',
            name='boolean_value',
            field=models.BooleanField(blank=True, help_text='antares.apps.core.models.user_parameter.boolean_value_help', null=True, verbose_name='antares.apps.core.models.user_parameter.boolean_value'),
        ),
    ]
