# Generated by Django 3.1.2 on 2020-10-05 16:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0007_auto_20201005_1342'),
        ('core', '0006_auto_20200830_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='actionparameterdefinition',
            name='data_type',
            field=models.TextField(choices=[('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('Datetime', 'Date time'), ('Integer', 'Integer'), ('Float', 'Float'), ('UUID', 'UUID'), ('Boolean', 'Boolean'), ('User', 'User'), ('client', 'Client'), ('document', 'Document'), ('Money', 'Money')], default='String', help_text='antares.apps.core.models.action_parameter_definition.data_type_help', max_length=8, verbose_name='antares.apps.core.models.action_parameter_definition.data_type'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='antares.apps.core.models.catalog.author'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='creation_date',
            field=models.DateTimeField(editable=False, verbose_name='antares.apps.core.models.catalog.creation_name'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='document_header',
            field=models.ForeignKey(blank=True, db_column='document_header', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.documentheader', verbose_name='antares.apps.core.models.catalog.document_header'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='sql_text',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='SQL Query'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='update_date',
            field=models.DateTimeField(editable=False, verbose_name='antares.apps.core.models.catalog.update_date'),
        ),
        migrations.AlterField(
            model_name='concepttype',
            name='concept_type_name',
            field=models.CharField(help_text='antares.apps.core.models.concept_type.concept_type_name_help', max_length=200, verbose_name='Concept Type name'),
        ),
        migrations.AlterField(
            model_name='concepttype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='antares.apps.core.models.concept_type.description_help', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='concepttype',
            name='id',
            field=models.SlugField(help_text='antares.apps.core.models.concept_type.primary_key_help', max_length=200, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='concepttype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='antares.apps.core.models.concept_type.parent_help', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.concepttype', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='data_type',
            field=models.TextField(choices=[('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('Datetime', 'Date time'), ('Integer', 'Integer'), ('Float', 'Float'), ('UUID', 'UUID'), ('Boolean', 'Boolean'), ('User', 'User'), ('client', 'Client'), ('document', 'Document'), ('Money', 'Money')], help_text='antares.apps.core.models.system_parameter.data_type_help', max_length=20, verbose_name='antares.apps.core.models.system_parameter.data_type'),
        ),
        migrations.AlterField(
            model_name='userparameter',
            name='data_type',
            field=models.TextField(choices=[('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('Datetime', 'Date time'), ('Integer', 'Integer'), ('Float', 'Float'), ('UUID', 'UUID'), ('Boolean', 'Boolean'), ('User', 'User'), ('client', 'Client'), ('document', 'Document'), ('Money', 'Money')], help_text='antares.apps.core.models.user_parameter.data_type_help', max_length=20, verbose_name='antares.apps.core.models.user_parameter.data_type'),
        ),
    ]
