# Generated by Django 3.0.4 on 2020-03-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190629_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.CharField(choices=[('Self', 'Self'), ('New Window', 'New Window'), ('Dialog', 'Dialog')], default='Self', max_length=30),
        ),
    ]
