# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180116_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Aplicación', 'verbose_name_plural': 'Aplicaciones'},
        ),
        migrations.AlterModelOptions(
            name='applicationparameter',
            options={'verbose_name': 'Parámetro de Aplicación', 'verbose_name_plural': 'Parámetros de Aplicación'},
        ),
    ]
