# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180214_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications'
            },
        ),
        migrations.AlterModelOptions(
            name='applicationparameter',
            options={
                'verbose_name': 'Application Parameter',
                'verbose_name_plural': 'Application Parameters'
            },
        ),
    ]
