# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 23:29
from __future__ import unicode_literals

from ..constants import *
from antares.apps.core.constants import *
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('accounting', '0002_auto_20180614_2029'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientObligation',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('account_type',
                 models.ForeignKey(
                     blank=True,
                     db_column='account_type',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='accounting.AccountType')),
                ('author',
                 models.ForeignKey(
                     db_column='author',
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('base_document',
                 models.ForeignKey(
                     blank=True,
                     db_column='base_obligation',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='client_obligation_base_document_set',
                     to='document.DocumentHeader')),
                ('client',
                 models.ForeignKey(
                     blank=True,
                     db_column='client',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.Client')),
                ('concept_type',
                 models.ForeignKey(
                     blank=True,
                     db_column='concept_type',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='core.ConceptType')),
            ],
            options={
                'verbose_name':
                'antares.apps.obligation.models.client_obligation.table_name',
                'verbose_name_plural':
                'antares.apps.obligation.models.client_obligation.table_name_plural',
                'db_table':
                'obl_client_obligation',
            },
        ),
        migrations.CreateModel(
            name='ObligationRule',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('base_date', models.DateTimeField()),
                ('description',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('obligation_condition', models.TextField(
                    blank=True, null=True)),
                ('end_date_expression', models.TextField(
                    blank=True, null=True)),
                ('form_condition', models.TextField(blank=True, null=True)),
                ('init_date_expression', models.TextField(
                    blank=True, null=True)),
                ('last_run',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_run',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('obligation_type',
                 enumfields.fields.EnumField(
                     enum=ObligationType, max_length=30)),
                ('origin',
                 enumfields.fields.EnumField(
                     enum=ObligationOriginType, max_length=30)),
                ('periodicity_type',
                 enumfields.fields.EnumField(
                     enum=ObligationPeriodicityType, max_length=30)),
                ('script_engine_type',
                 enumfields.fields.EnumField(
                     enum=ScriptEngineType, max_length=30)),
                ('time_unit_type',
                 enumfields.fields.EnumField(enum=TimeUnitType,
                                             max_length=30)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('update_date', models.DateTimeField(editable=False)),
                ('saturdays_are_holiday', models.BooleanField(default=False)),
                ('sundays_are_holiday', models.BooleanField(default=False)),
                ('consider_holidays', models.BooleanField(default=True)),
                ('account_type',
                 models.ForeignKey(
                     blank=True,
                     db_column='account_type',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='accounting.AccountType')),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('concept_type',
                 models.ForeignKey(
                     blank=True,
                     db_column='concept_type',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='core.ConceptType')),
                ('form_definition',
                 models.ForeignKey(
                     blank=True,
                     db_column='form_definition',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='document.FormDefinition')),
            ],
            options={
                'verbose_name':
                'antares.apps.obligation.models.obligation_rule.table_name',
                'verbose_name_plural':
                'antares.apps.obligation.models.obligation_rule.table_name_plural',
                'db_table':
                'obl_rule',
            },
        ),
        migrations.CreateModel(
            name='ObligationVector',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('due_date', models.DateTimeField()),
                ('compliance_date', models.DateTimeField(
                    blank=True, null=True)),
                ('period', models.IntegerField()),
                ('status',
                 enumfields.fields.EnumField(
                     enum=ObligationStatusType, max_length=30)),
                ('obligation_type',
                 enumfields.fields.EnumField(
                     enum=ObligationType, max_length=30)),
                ('status_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('account_type',
                 models.ForeignKey(
                     db_column='account_type',
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_status_account_type_set',
                     to='accounting.AccountType')),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_vector_author_set',
                     to=settings.AUTH_USER_MODEL)),
                ('base_document',
                 models.ForeignKey(
                     blank=True,
                     db_column='base_document',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_status_base_document_set',
                     to='document.DocumentHeader')),
                ('client',
                 models.ForeignKey(
                     blank=True,
                     db_column='client',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_status_client_set',
                     to='client.Client')),
                ('client_obligation',
                 models.ForeignKey(
                     blank=True,
                     db_column='client_obligation',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_status_client_obligation_set',
                     to='obligation.ClientObligation')),
                ('compliance_document',
                 models.ForeignKey(
                     blank=True,
                     db_column='compliance_document',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_vector_compliance_document_set',
                     to='document.DocumentHeader')),
                ('concept_type',
                 models.ForeignKey(
                     blank=True,
                     db_column='concept_type',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='core.ConceptType')),
                ('source_document',
                 models.ForeignKey(
                     blank=True,
                     db_column='source_document',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_vector_source_document_set',
                     to='document.DocumentHeader')),
            ],
            options={
                'verbose_name':
                'antares.apps.obligation.models.obligation_vector.table_name',
                'verbose_name_plural':
                'antares.apps.obligation.models.obligation_vector.table_name_plural',
                'db_table':
                'obl_vector',
            },
        ),
        migrations.CreateModel(
            name='ObligationVectorLog',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('status',
                 models.CharField(
                     max_length=30, verbose_name=ObligationStatusType)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('log_date', models.DateTimeField()),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_vector_log_author_set',
                     to=settings.AUTH_USER_MODEL)),
                ('obligation_status',
                 models.ForeignKey(
                     blank=True,
                     db_column='obligation',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='obligation_vector_log_set',
                     to='obligation.ObligationVector')),
            ],
            options={
                'verbose_name':
                'antares.apps.obligation.models.obligation_vector_log.table_name',
                'verbose_name_plural':
                'antares.apps.obligation.models.obligation_vector_log.table_name_plural',
                'db_table':
                'obl_vector_log',
            },
        ),
        migrations.AddField(
            model_name='clientobligation',
            name='obligation_rule',
            field=models.ForeignKey(
                blank=True,
                db_column='obligation_rule',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='obligation.ObligationRule'),
        ),
        migrations.AlterUniqueTogether(
            name='obligationvector',
            unique_together=set([('client', 'concept_type', 'period',
                                  'account_type', 'base_document')]),
        ),
        migrations.AlterUniqueTogether(
            name='clientobligation',
            unique_together=set([('client', 'concept_type')]),
        ),
    ]
