# Generated by Django 2.2.9 on 2020-02-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligation', '0002_auto_20180624_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationrule',
            name='name',
            field=models.CharField(default='OBLIGATION_RULE_1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
