# Generated by Django 3.0.4 on 2020-03-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligation', '0003_obligationrule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationrule',
            name='obligation_type',
            field=models.CharField(choices=[('File', 'File'), ('Pay', 'Pay'), ('Inform', 'Inform')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obligationrule',
            name='origin',
            field=models.CharField(choices=[('Client Base', 'Client Base'), ('Form', 'Form')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obligationrule',
            name='periodicity_type',
            field=models.CharField(choices=[('Fixed date', 'Fixed Date'), ('Fixed period', 'Fixed Period'), ('Free form', 'Free Form')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obligationrule',
            name='script_engine_type',
            field=models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obligationrule',
            name='time_unit_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day'), ('Hour', 'Hour'), ('Minute', 'Minute'), ('Second', 'Second')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obligationvector',
            name='obligation_type',
            field=models.CharField(choices=[('File', 'File'), ('Pay', 'Pay'), ('Inform', 'Inform')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obligationvector',
            name='status',
            field=models.CharField(choices=[('Not Exigible', 'Not Exigible'), ('Pending', 'Pending'), ('Compliant', 'Compliant'), ('Cancelled', 'Cancelled'), ('Late', 'Late')], max_length=30),
        ),
        migrations.AlterField(
            model_name='obligationvectorlog',
            name='status',
            field=models.CharField(choices=[('Not Exigible', 'Not Exigible'), ('Pending', 'Pending'), ('Compliant', 'Compliant'), ('Cancelled', 'Cancelled'), ('Late', 'Late')], max_length=30),
        ),
    ]
