# Generated by Django 2.0.6 on 2018-06-24 20:59

import uuid

from django.db import migrations, models
import enumfields.fields

from antares.apps.core.constants import *

from ..constants import *


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('message_type', enumfields.fields.EnumField(enum=MessageType, max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(editable=False, help_text='antares.apps.message.models.message.creation_name_help', verbose_name='antares.apps.message.models.message.creation_name')),
                ('update_date', models.DateTimeField(editable=False, help_text='antares.apps.message.models.message.update_date_help', verbose_name='antares.apps.message.models.message.update_date')),
            ],
            options={
                'verbose_name': 'antares.apps.message.models.message.table_name',
                'verbose_name_plural': 'antares.apps.message.models.message.table_name_plural',
                'db_table': 'msg_message',
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', enumfields.fields.EnumField(enum=SystemModuleType, max_length=30)),
                ('status', enumfields.fields.EnumField(default='Pending', enum=MessageStatusType, max_length=30)),
                ('creation_date', models.DateTimeField(editable=False, help_text='antares.apps.message.models.message_status.creation_name_help', verbose_name='antares.apps.message.models.message_status.creation_name')),
                ('update_date', models.DateTimeField(editable=False, help_text='antares.apps.message.models.message_status.update_date_help', verbose_name='antares.apps.message.models.message_status.update_date')),
            ],
            options={
                'verbose_name': 'antares.apps.message.models.message_status.table_name',
                'verbose_name_plural': 'antares.apps.message.models.message_status.table_name_plural',
                'db_table': 'msg_message_status',
            },
        ),
    ]
