# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 23:29
from __future__ import unicode_literals

from ..constants import *
from antares.apps.core.constants import *
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_auto_20180614_2029'),
        ('client', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('message_type',
                 enumfields.fields.EnumField(enum=MessageType, max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('creation_date',
                 models.DateTimeField(
                     editable=False,
                     help_text=
                     'antares.apps.message.models.message.creation_name_help',
                     verbose_name=
                     'antares.apps.message.models.message.creation_name')),
                ('update_date',
                 models.DateTimeField(
                     editable=False,
                     help_text=
                     'antares.apps.message.models.message.update_date_help',
                     verbose_name=
                     'antares.apps.message.models.message.update_date')),
                ('account_type',
                 models.ForeignKey(
                     blank=True,
                     db_column='account_type',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='accounting.AccountType')),
                ('author',
                 models.ForeignKey(
                     editable=False,
                     help_text=
                     'antares.apps.message.models.message.author_help',
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='antares.apps.message.models.message.author')
                 ),
                ('client',
                 models.ForeignKey(
                     blank=True,
                     db_column='client',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.Client')),
                ('concept_type',
                 models.ForeignKey(
                     blank=True,
                     db_column='concept_type',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='core.ConceptType')),
                ('document',
                 models.ForeignKey(
                     blank=True,
                     db_column='document',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='document.DocumentHeader')),
                ('flow_case',
                 models.ForeignKey(
                     blank=True,
                     db_column='flow_case',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='flow.FlowCase')),
                ('flow_definition',
                 models.ForeignKey(
                     blank=True,
                     db_column='flow_definition',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='flow.FlowDefinition')),
                ('form_definition',
                 models.ForeignKey(
                     blank=True,
                     db_column='form_definition',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='document.FormDefinition')),
            ],
            options={
                'verbose_name':
                'antares.apps.message.models.message.table_name',
                'verbose_name_plural':
                'antares.apps.message.models.message.table_name_plural',
                'db_table':
                'msg_message',
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('module',
                 enumfields.fields.EnumField(
                     enum=SystemModuleType, max_length=30)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Pending', enum=MessageStatusType,
                     max_length=30)),
                ('creation_date',
                 models.DateTimeField(
                     editable=False,
                     help_text=
                     'antares.apps.message.models.message_status.creation_name_help',
                     verbose_name=
                     'antares.apps.message.models.message_status.creation_name'
                 )),
                ('update_date',
                 models.DateTimeField(
                     editable=False,
                     help_text=
                     'antares.apps.message.models.message_status.update_date_help',
                     verbose_name=
                     'antares.apps.message.models.message_status.update_date')
                 ),
                ('author',
                 models.ForeignKey(
                     editable=False,
                     help_text=
                     'antares.apps.message.models.message_status.author_help',
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL,
                     verbose_name=
                     'antares.apps.message.models.message_status.author')),
                ('core_object',
                 models.ForeignKey(
                     db_column='message',
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='status_set',
                     to='message.Message')),
            ],
            options={
                'verbose_name':
                'antares.apps.message.models.message_status.table_name',
                'verbose_name_plural':
                'antares.apps.message.models.message_status.table_name_plural',
                'db_table':
                'msg_message_status',
            },
        ),
    ]
