# Generated by Django 3.0.4 on 2020-03-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180624_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('Form Definition', 'Form Definition'), ('Flow Definition', 'Flow Definition'), ('Current Account', 'Current Account'), ('Flow Case', 'Flow Case'), ('Document', 'Document'), ('External System', 'antares.apps.message.constants.MessageType.EXTERNAL_SYSTEM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='module',
            field=models.CharField(choices=[('Accounting', 'antares.apps.core.constants.SystemModuleType.ACCOUNTING'), ('Client', 'antares.apps.core.constants.SystemModuleType.CLIENT'), ('Core', 'antares.apps.core.constants.SystemModuleType.CORE'), ('Document', 'antares.apps.core.constants.SystemModuleType.DOCUMENT'), ('Flow', 'antares.apps.core.constants.SystemModuleType.FLOW'), ('Notifications', 'antares.apps.core.constants.SystemModuleType.NOTIFICATIONS'), ('Obligation', 'antares.apps.core.constants.SystemModuleType.OBLIGATION'), ('Subscription', 'antares.apps.core.constants.SystemModuleType.SUBSCRIPTION'), ('Terminal', 'antares.apps.core.constants.SystemModuleType.TERMINAL'), ('Message', 'antares.apps.core.constants.SystemModuleType.MESSAGE'), ('Third Party', 'antares.apps.core.constants.SystemModuleType.THIRD_PARTY'), ('Web', 'antares.apps.core.constants.SystemModuleType.WEB')], max_length=30),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'antares.apps.message.constants.MessageStatusType.PENDING'), ('Processed', 'antares.apps.message.constants.MessageStatusType.PROCESSED'), ('With Errors', 'antares.apps.message.constants.MessageStatusType.WITH_ERRORS'), ('On hold', 'antares.apps.message.constants.MessageStatusType.ON_HOLD'), ('Cancelled', 'antares.apps.message.constants.MessageStatusType.CANCELLED'), ('External System', 'antares.apps.message.constants.MessageStatusType.EXTERNAL_SYSTEM')], default='Pending', max_length=30),
        ),
    ]
