# Generated by Django 3.0.4 on 2020-03-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20200120_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='data_type',
            field=models.CharField(choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], help_text='antares.apps.document.models.document_field.data_type_help', max_length=30, verbose_name='antares.apps.document.models.document_field.data_type'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='association_type',
            field=models.CharField(choices=[('None', 'antares.apps.document.constants.DocumentAssociationType.NONE')], default='None', help_text='antares.apps.document.models.document_header.association_type_help', max_length=30, verbose_name='antares.apps.document.models.document_header.association_type'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='origin',
            field=models.CharField(choices=[('Online', 'antares.apps.document.constants.DocumentOriginType.ONLINE'), ('Unknown', 'antares.apps.document.constants.DocumentOriginType.UNKNOWN')], default='Unknown', help_text='antares.apps.document.models.document_header.origin_help', max_length=30, verbose_name='antares.apps.document.models.document_header.origin'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='status',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('Deleted', 'Deleted'), ('Saved', 'Saved'), ('Cancelled', 'Cancelled')], default='Drafted', help_text='antares.apps.document.models.document_header.status_help', max_length=30, verbose_name='antares.apps.document.models.document_header.status'),
        ),
        migrations.AlterField(
            model_name='documenthrn',
            name='status',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('Deleted', 'Deleted'), ('Saved', 'Saved'), ('Cancelled', 'Cancelled')], default='Drafted', help_text='antares.apps.document.models.document_hrn.status_help', max_length=30, verbose_name='antares.apps.document.models.document_hrn.status'),
        ),
        migrations.AlterField(
            model_name='documenttablecontent',
            name='data_type',
            field=models.CharField(blank=True, choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='formclass',
            name='status',
            field=models.CharField(choices=[('Development', 'Development'), ('Production', 'Production'), ('Deactivated', 'Deactivated')], default='Development', max_length=30),
        ),
        migrations.AlterField(
            model_name='formclass',
            name='type',
            field=models.CharField(choices=[('Administrative', 'Administrative'), ('Obligation Based', 'Obligation Based')], default='Administrative', max_length=30),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='status',
            field=models.CharField(choices=[('Development', 'Development'), ('Production', 'Production'), ('Deactivated', 'Deactivated')], default='Development', max_length=30),
        ),
        migrations.AlterField(
            model_name='formdefinitionacl',
            name='access_type',
            field=models.CharField(choices=[('Create', 'antares.apps.document.constants.FormDefinitionACLAccessType.CREATE'), ('Search', 'antares.apps.document.constants.FormDefinitionACLAccessType.SEARCH'), ('All', 'antares.apps.document.constants.FormDefinitionACLAccessType.ALL'), ('None', 'antares.apps.document.constants.FormDefinitionACLAccessType.NONE')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='indexedfield',
            name='data_type',
            field=models.CharField(choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], help_text='antares.apps.document.models.indexed_field.data_type_help', max_length=30, verbose_name='antares.apps.document.models.indexed_field.data_type'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('Deleted', 'Deleted'), ('Saved', 'Saved'), ('Cancelled', 'Cancelled')], help_text='antares.apps.document.models.status_log.status_help', max_length=30, verbose_name='antares.apps.document.models.status_log.status'),
        ),
    ]
