# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_indexedfield_uuid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='uuid_value',
            field=models.UUIDField(blank=True, help_text='antares.apps.document.models.document_field.uuid_value_help', null=True, verbose_name='antares.apps.document.models.document_field.uuid_value'),
        ),
    ]
