# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_documentfield_uuid_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacl',
            options={
                'verbose_name': 'ACL de Documento',
                'verbose_name_plural': 'ACLs de Documento'
            },
        ),
        migrations.AlterModelOptions(
            name='formclass',
            options={
                'verbose_name': 'Clase de Formulario',
                'verbose_name_plural': 'Clases de Formulario'
            },
        ),
        migrations.AlterModelOptions(
            name='formdefinition',
            options={
                'verbose_name': 'Definición de Formulario',
                'verbose_name_plural': 'Definiciones de Formulario'
            },
        ),
        migrations.AlterModelOptions(
            name='formdefinitionacl',
            options={
                'verbose_name': 'ACL de la Definición de Formulario',
                'verbose_name_plural': 'ACLs de la Definición de Formulario'
            },
        ),
    ]
