# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20180214_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='default_currency',
            field=models.CharField(blank=True, help_text='antares.apps.document.models.document_header.default_currency_help', max_length=30, null=True, verbose_name='antares.apps.document.models.document_header.default_currency'),
        ),
    ]
