# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_documentheader_default_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacl',
            options={
                'verbose_name': 'Document Access Control List',
                'verbose_name_plural': 'Document Access Control Lists'
            },
        ),
        migrations.AlterModelOptions(
            name='formclass',
            options={
                'verbose_name': 'Form Class',
                'verbose_name_plural': 'Form Classes'
            },
        ),
        migrations.AlterModelOptions(
            name='formdefinition',
            options={
                'verbose_name': 'Form Definition',
                'verbose_name_plural': 'Form Definitions'
            },
        ),
        migrations.AlterModelOptions(
            name='formdefinitionacl',
            options={
                'verbose_name': 'Form Definition Access Control List',
                'verbose_name_plural': 'Form Definition Access Control Lists'
            },
        ),
    ]
