# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 23:29
from __future__ import unicode_literals

from ..constants import *
from antares.apps.core.constants import *
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0002_auto_20180614_2029'),
        ('document', '0002_auto_20180614_2029'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('content', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=2000)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Posted',
                     enum=NotificationStatusType,
                     max_length=30)),
                ('update_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     db_column='author',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('document',
                 models.ForeignKey(
                     blank=True,
                     db_column='document_header',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='document.DocumentHeader')),
                ('flow_case',
                 models.ForeignKey(
                     blank=True,
                     db_column='flow_case',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='flow.FlowCase')),
                ('recipient',
                 models.ForeignKey(
                     blank=True,
                     db_column='recipient',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='notification_recipient_set',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name':
                'antares.apps.notifications.models.notification_record.table_name',
                'verbose_name_plural':
                'antares.apps.notifications.models.notification_record.table_name_plural',
                'db_table':
                'not_record',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('user_code_variable',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('date_variable',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('content_variable',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('content_template',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_variable',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('update_date', models.DateTimeField(editable=False)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('active', models.BooleanField(default='true')),
                ('author',
                 models.ForeignKey(
                     db_column='author',
                     editable=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('form_definition',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='notification_rule_set',
                     to='document.FormDefinition')),
                ('target_role',
                 models.ForeignKey(
                     blank=True,
                     db_column='target_role',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='user.Role')),
                ('target_unit',
                 models.ForeignKey(
                     blank=True,
                     db_column='target_unit',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='user.OrgUnit')),
                ('target_user',
                 models.ForeignKey(
                     blank=True,
                     db_column='target_user',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='notification_rule_target_user_set',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name':
                'antares.apps.notifications.models.notification_rule.table_name',
                'verbose_name_plural':
                'antares.apps.notifications.models.notification_rule.table_name_plural',
                'db_table':
                'not_rule',
            },
        ),
    ]
