# Generated by Django 2.0.6 on 2018-06-24 20:59

from antares.apps.core.constants import *
import uuid

import ckeditor.fields
from django.db import migrations, models
import enumfields.fields

from ..constants import *


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=2000)),
                ('status', enumfields.fields.EnumField(default='Posted', enum=NotificationStatusType, max_length=30)),
                ('update_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'antares.apps.notifications.models.notification_record.table_name',
                'verbose_name_plural': 'antares.apps.notifications.models.notification_record.table_name_plural',
                'db_table': 'not_record',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_code_variable', models.CharField(blank=True, max_length=200, null=True)),
                ('date_variable', models.CharField(blank=True, max_length=200, null=True)),
                ('content_variable', models.CharField(blank=True, max_length=200, null=True)),
                ('content_template', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_variable', models.CharField(blank=True, max_length=200, null=True)),
                ('update_date', models.DateTimeField(editable=False)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('active', models.BooleanField(default='true')),
            ],
            options={
                'verbose_name': 'antares.apps.notifications.models.notification_rule.table_name',
                'verbose_name_plural': 'antares.apps.notifications.models.notification_rule.table_name_plural',
                'db_table': 'not_rule',
            },
        ),
    ]
