# Generated by Django 3.0.4 on 2020-03-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180624_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecord',
            name='status',
            field=models.CharField(choices=[('Viewed', 'antares.apps.notifications.constants.NotificationStatusType.VIEWED'), ('Posted', 'antares.apps.notifications.constants.NotificationStatusType.POSTED')], default='Posted', max_length=30),
        ),
    ]
