# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20171209_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='form_definition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notification_rule_set',
                to='document.FormDefinition'),
        ),
    ]
