# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    help_text=
                    'antares.apps.terminal.models.terminal_log.id_help',
                    primary_key=True,
                    serialize=False,
                    verbose_name='antares.apps.terminal.models.terminal_log.id'
                )),
                ('post_date', models.DateTimeField(
                    help_text=
                    'antares.apps.terminal.models.terminal_log.post_date_help',
                    verbose_name=
                    'antares.apps.terminal.models.terminal_log.post_date')),
                ('command', models.CharField(
                    help_text=
                    'antares.apps.terminal.models.terminal_log.command_help',
                    max_length=2000,
                    verbose_name=
                    'antares.apps.terminal.models.terminal_log.command')),
                ('result', models.TextField(
                    help_text=
                    'antares.apps.terminal.models.terminal_log.result_help',
                    verbose_name=
                    'antares.apps.terminal.models.terminal_log.result')),
            ],
            options={
                'verbose_name':
                'antares.apps.terminal.models.terminal_log.table_name',
                'db_table':
                'adm_terminal_log',
                'verbose_name_plural':
                'antares.apps.terminal.models.terminal_log.table_name_plural',
            }, ),
    ]
