# Generated by Django 2.0.6 on 2018-06-24 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='antares.apps.terminal.models.terminal_log.id_help', primary_key=True, serialize=False, verbose_name='antares.apps.terminal.models.terminal_log.id')),
                ('post_date', models.DateTimeField(help_text='antares.apps.terminal.models.terminal_log.post_date_help', verbose_name='antares.apps.terminal.models.terminal_log.post_date')),
                ('command', models.CharField(help_text='antares.apps.terminal.models.terminal_log.command_help', max_length=2000, verbose_name='antares.apps.terminal.models.terminal_log.command')),
                ('result', models.TextField(help_text='antares.apps.terminal.models.terminal_log.result_help', verbose_name='antares.apps.terminal.models.terminal_log.result')),
            ],
            options={
                'verbose_name': 'antares.apps.terminal.models.terminal_log.table_name',
                'verbose_name_plural': 'antares.apps.terminal.models.terminal_log.table_name_plural',
                'db_table': 'adm_terminal_log',
            },
        ),
    ]
