# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 23:29
from __future__ import unicode_literals

from ..constants import *
from antares.apps.core.constants import *
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressItem',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('address_type',
                 enumfields.fields.EnumField(
                     default='Real', enum=AddressType, max_length=30)),
                ('country_code',
                 models.CharField(blank=True, max_length=2, null=True)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Active', enum=ItemStatusType, max_length=20)),
                ('is_principal', models.BooleanField(default=True)),
                ('line_1',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('line_2',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code',
                 models.CharField(blank=True, max_length=10, null=True)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'cli_address_item',
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id',
                 models.CharField(
                     max_length=50, primary_key=True, serialize=False)),
                ('description',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('data_type',
                 enumfields.fields.EnumField(
                     enum=FieldDataType, max_length=20)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Definición de Atributo',
                'verbose_name_plural': 'Definiciones de Atributo',
                'db_table': 'cli_attribute_definition',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('full_name',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('first_name',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('last_name',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('title',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('registration_date', models.DateTimeField()),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('defunction_date', models.DateTimeField(
                    blank=True, null=True)),
                ('gender',
                 enumfields.fields.EnumField(
                     blank=True,
                     enum=ClientGenderType,
                     max_length=17,
                     null=True)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Active', enum=ClientStatusType, max_length=17)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='client_author_set',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cli_client',
            },
        ),
        migrations.CreateModel(
            name='ClientAttribute',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('boolean_value', models.NullBooleanField()),
                ('data_type',
                 enumfields.fields.EnumField(
                     enum=FieldDataType, max_length=20)),
                ('date_value', models.DateTimeField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('integer_value', models.BigIntegerField(
                    blank=True, null=True)),
                ('string_value',
                 models.CharField(blank=True, max_length=2000, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('attribute_definition',
                 models.ForeignKey(
                     blank=True,
                     db_column='attribute_definition',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.AttributeDefinition')),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('client',
                 models.ForeignKey(
                     blank=True,
                     db_column='client',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.Client')),
            ],
            options={
                'verbose_name':
                'antares.apps.client.models.client_attribute.table_name',
                'verbose_name_plural':
                'antares.apps.client.models.client_attribute.table_name_plural',
                'db_table':
                'cli_client_attribute',
            },
        ),
        migrations.CreateModel(
            name='ClientBranch',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('branch_name', models.CharField(max_length=200)),
                ('branch_number', models.IntegerField(default=0)),
                ('description',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField()),
                ('occupation_description',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('client',
                 models.ForeignKey(
                     db_column='client',
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='branch_set',
                     to='client.Client')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'db_table': 'cli_client_branch',
            },
        ),
        migrations.CreateModel(
            name='ClientBusinessClassification',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clasificación de negocios de cliente',
                'verbose_name_plural':
                'Clasificaciones de negocios de cliente',
                'db_table': 'cli_client_business_classification',
            },
        ),
        migrations.CreateModel(
            name='ClientIdentificationType',
            fields=[
                ('id',
                 models.CharField(
                     max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('description',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('update_date', models.DateTimeField(editable=False)),
                ('author',
                 models.ForeignKey(
                     editable=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
                'db_table': 'cli_identification_type',
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id',
                 models.CharField(
                     max_length=255, primary_key=True, serialize=False)),
                ('archetype',
                 enumfields.fields.EnumField(
                     enum=ClientArchetype, max_length=20)),
                ('short_name', models.CharField(max_length=1000)),
                ('description',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'db_table': 'cli_client_type',
            },
        ),
        migrations.CreateModel(
            name='ClientUserRelation',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('relation_type',
                 enumfields.fields.EnumField(
                     enum=ClientRelationType, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='client_user_relation_author_set',
                     to=settings.AUTH_USER_MODEL)),
                ('child_client',
                 models.ForeignKey(
                     db_column='child_client',
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='child_client_relation_set',
                     to='client.Client')),
                ('parent_user',
                 models.ForeignKey(
                     db_column='parent_user',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='client_user_relation_set',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name':
                'antares.apps.client.models.client_user_relation.table_name',
                'verbose_name_plural':
                'antares.apps.client.models.client_user_relation.table_name_plural',
                'db_table':
                'cli_user_client_relation',
            },
        ),
        migrations.CreateModel(
            name='ClientUserRelationPermission',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('relation_type',
                 enumfields.fields.EnumField(
                     enum=ClientRelationPermissionType, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='client_user_relation_permission_author_set',
                     to=settings.AUTH_USER_MODEL)),
                ('client_relation',
                 models.ForeignKey(
                     db_column='client_user_relation',
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='permission_set',
                     to='client.ClientUserRelation')),
            ],
            options={
                'verbose_name':
                'antares.apps.client.models.client_user_relation_permission.table_name',
                'verbose_name_plural':
                'antares.apps.client.models.client_user_relation_permission.table_name_plural',
                'db_table':
                'cli_client_user_relation_permission',
            },
        ),
        migrations.CreateModel(
            name='EmailItem',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Active', enum=ItemStatusType, max_length=20)),
                ('is_principal', models.BooleanField(default=True)),
                ('email_type',
                 enumfields.fields.EnumField(enum=EmailType, max_length=20)),
                ('email', models.CharField(max_length=256)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('client_branch',
                 models.ForeignKey(
                     blank=True,
                     db_column='client_branch',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.ClientBranch')),
            ],
            options={
                'verbose_name': 'Correo Electrónico',
                'verbose_name_plural': 'Correos Electrónicos',
                'db_table': 'cli_email_item',
            },
        ),
        migrations.CreateModel(
            name='IdentificationItem',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Active', enum=ItemStatusType, max_length=20)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('update_date', models.DateTimeField(editable=False)),
                ('author',
                 models.ForeignKey(
                     editable=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('client',
                 models.ForeignKey(
                     db_column='client',
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.Client')),
                ('type',
                 models.ForeignKey(
                     db_column='type',
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.ClientIdentificationType')),
            ],
            options={
                'verbose_name': 'Identificación de Cliente',
                'verbose_name_plural': 'Identificaciones de Cliente',
                'db_table': 'cli_identification_item',
            },
        ),
        migrations.CreateModel(
            name='IsicPosition',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     help_text=
                     'antares.apps.client.models.isic_position.primary_key_help',
                     primary_key=True,
                     serialize=False)),
                ('isic_name', models.CharField(max_length=2000)),
                ('isic_code', models.CharField(max_length=200)),
                ('language',
                 enumfields.fields.EnumField(enum=LanguageType,
                                             max_length=20)),
                ('description',
                 ckeditor.fields.RichTextField(blank=True, null=True)),
                ('creation_date',
                 models.DateTimeField(
                     editable=False,
                     help_text=
                     'antares.apps.client.models.isic_position.creation_name_help',
                     verbose_name=
                     'antares.apps.client.models.isic_position.creation_name')
                 ),
                ('update_date',
                 models.DateTimeField(
                     editable=False,
                     help_text=
                     'antares.apps.client.models.isic_position.update_date_help',
                     verbose_name=
                     'antares.apps.client.models.isic_position.update_date')),
                ('lft',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('level',
                 models.PositiveIntegerField(db_index=True, editable=False)),
                ('author',
                 models.ForeignKey(
                     editable=False,
                     help_text=
                     'antares.apps.client.models.isic_position.author_help',
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL,
                     verbose_name=
                     'antares.apps.client.models.isic_position.author')),
                ('parent',
                 mptt.fields.TreeForeignKey(
                     blank=True,
                     help_text=
                     'antares.apps.client.models.isic_position.parent_help',
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='children',
                     to='client.IsicPosition',
                     verbose_name=
                     'antares.apps.client.models.isic_position.parent')),
            ],
            options={
                'verbose_name': 'Posición ISIC',
                'verbose_name_plural': 'Posiciones ISIC',
                'db_table': 'cli_isic_position',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkItem',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Active', enum=ItemStatusType, max_length=20)),
                ('is_principal', models.BooleanField(default=True)),
                ('item', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('social_network_type',
                 enumfields.fields.EnumField(
                     default='Skype',
                     enum=SocialNetworkItemType,
                     max_length=100)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('client_branch',
                 models.ForeignKey(
                     blank=True,
                     db_column='client_branch',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.ClientBranch')),
            ],
            options={
                'verbose_name': 'Red social de Cliente',
                'verbose_name_plural': 'Redes sociales de Cliente',
                'db_table': 'cli_social_network_item',
            },
        ),
        migrations.CreateModel(
            name='TelephoneItem',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('status',
                 enumfields.fields.EnumField(
                     default='Active', enum=ItemStatusType, max_length=20)),
                ('is_principal', models.BooleanField(default=True)),
                ('telephone',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_type',
                 models.CharField(
                     default=TelephoneItemType('Home'),
                     max_length=9,
                     verbose_name=TelephoneItemType)),
                ('creation_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_date',
                 models.DateTimeField(blank=True, editable=False, null=True)),
                ('author',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
                ('client_branch',
                 models.ForeignKey(
                     blank=True,
                     db_column='client_branch',
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='client.ClientBranch')),
            ],
            options={
                'verbose_name': 'Teléfono de Cliente',
                'verbose_name_plural': 'Teléfonos de Cliente',
                'db_table': 'cli_telephone_item',
            },
        ),
        migrations.AddField(
            model_name='clientbusinessclassification',
            name='business_classification',
            field=mptt.fields.TreeForeignKey(
                db_column='isic_position',
                on_delete=django.db.models.deletion.PROTECT,
                to='client.IsicPosition'),
        ),
        migrations.AddField(
            model_name='clientbusinessclassification',
            name='client_branch',
            field=models.ForeignKey(
                db_column='client_branch',
                on_delete=django.db.models.deletion.PROTECT,
                to='client.ClientBranch'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(
                db_column='client_type',
                on_delete=django.db.models.deletion.PROTECT,
                to='client.ClientType'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='client',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressitem',
            name='client_branch',
            field=models.ForeignKey(
                blank=True,
                db_column='client_branch',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='client.ClientBranch'),
        ),
        migrations.AlterUniqueTogether(
            name='isicposition',
            unique_together=set([('isic_code', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='clientbranch',
            unique_together=set([('client', 'branch_number')]),
        ),
    ]
