# Generated by Django 3.0.4 on 2020-03-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190629_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressitem',
            name='address_type',
            field=models.CharField(choices=[('Real', 'antares.apps.client.constants.AddressType.REAL'), ('Legal', 'antares.apps.client.constants.AddressType.LEGAL'), ('Especial', 'antares.apps.client.constants.AddressType.ESPECIAL')], default='Real', max_length=30),
        ),
        migrations.AlterField(
            model_name='addressitem',
            name='status',
            field=models.CharField(choices=[('Active', 'antares.apps.client.constants.StatusType.ACTIVE'), ('Inactive', 'antares.apps.client.constants.StatusType.INACTIVE')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Defunct', 'antares.apps.client.constants.ClientStatusType.DEFUCT'), ('Defunct Candidate', 'Defunct Candidate')], default='Active', max_length=17),
        ),
        migrations.AlterField(
            model_name='clientattribute',
            name='data_type',
            field=models.CharField(choices=[('String', 'antares.apps.core.constants.FieldDataType.STRING'), ('Text', 'antares.apps.core.constants.FieldDataType.TEXT'), ('Date', 'antares.apps.core.constants.FieldDataType.DATE'), ('Datetime', 'antares.apps.core.constants.FieldDataType.DATETIME'), ('Integer', 'antares.apps.core.constants.FieldDataType.INTEGER'), ('Float', 'antares.apps.core.constants.FieldDataType.FLOAT'), ('UUID', 'antares.apps.core.constants.FieldDataType.UUID'), ('Boolean', 'antares.apps.core.constants.FieldDataType.BOOLEAN'), ('User', 'antares.apps.core.constants.FieldDataType.USER'), ('client', 'antares.apps.core.constants.FieldDataType.CLIENT'), ('document', 'antares.apps.core.constants.FieldDataType.DOCUMENT'), ('Money', 'antares.apps.core.constants.FieldDataType.MONEY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clienttype',
            name='archetype',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientuserrelation',
            name='relation_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Director', 'Director'), ('Accountant', 'Accountant'), ('Lawyer', 'Lawyer'), ('Clerk', 'Clerk'), ('Worker', 'antares.apps.client.constants.ClientRelationType.GENERIC_WORKER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientuserrelationpermission',
            name='relation_type',
            field=models.CharField(choices=[('All', 'All'), ('File', 'File')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_type',
            field=models.CharField(choices=[('Official', 'Official'), ('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='status',
            field=models.CharField(choices=[('Active', 'antares.apps.client.constants.StatusType.ACTIVE'), ('Inactive', 'antares.apps.client.constants.StatusType.INACTIVE')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='identificationitem',
            name='status',
            field=models.CharField(choices=[('Active', 'antares.apps.client.constants.StatusType.ACTIVE'), ('Inactive', 'antares.apps.client.constants.StatusType.INACTIVE')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='isicposition',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('pr', 'Portuguese')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialnetworkitem',
            name='social_network_type',
            field=models.CharField(choices=[('Skype', 'Skype')], default='Skype', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialnetworkitem',
            name='status',
            field=models.CharField(choices=[('Active', 'antares.apps.client.constants.StatusType.ACTIVE'), ('Inactive', 'antares.apps.client.constants.StatusType.INACTIVE')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='telephoneitem',
            name='status',
            field=models.CharField(choices=[('Active', 'antares.apps.client.constants.StatusType.ACTIVE'), ('Inactive', 'antares.apps.client.constants.StatusType.INACTIVE')], default='Active', max_length=20),
        ),
    ]
