# Generated by Django 3.1.2 on 2020-10-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200830_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientattribute',
            options={'verbose_name': 'Client Attribute', 'verbose_name_plural': 'Client Attributes'},
        ),
        migrations.AlterField(
            model_name='addressitem',
            name='address_type',
            field=models.CharField(choices=[('Real', 'Real'), ('Legal', 'Legal'), ('Especial', 'Especial')], default='Real', max_length=30),
        ),
        migrations.AlterField(
            model_name='addressitem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('Datetime', 'Date time'), ('Integer', 'Integer'), ('Float', 'Float'), ('UUID', 'UUID'), ('Boolean', 'Boolean'), ('User', 'User'), ('client', 'Client'), ('document', 'Document'), ('Money', 'Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Defunct', 'Defunct'), ('Defunct Candidate', 'Defunct Candidate')], default='Active', max_length=17),
        ),
        migrations.AlterField(
            model_name='clientattribute',
            name='data_type',
            field=models.CharField(choices=[('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('Datetime', 'Date time'), ('Integer', 'Integer'), ('Float', 'Float'), ('UUID', 'UUID'), ('Boolean', 'Boolean'), ('User', 'User'), ('client', 'Client'), ('document', 'Document'), ('Money', 'Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='identificationitem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialnetworkitem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='telephoneitem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
